{"level":"error","message":"Gemini AI analysis failed: Expected ',' or ']' after array element in JSON at position 3788 (line 98 column 5)","stack":"SyntaxError: Expected ',' or ']' after array element in JSON at position 3788 (line 98 column 5)\n    at JSON.parse (<anonymous>)\n    at ResumeParser.<anonymous> (F:\\Github\\resume_ai\\backend\\src\\services\\resumeParser.ts:183:33)\n    at Generator.next (<anonymous>)\n    at fulfilled (F:\\Github\\resume_ai\\backend\\src\\services\\resumeParser.ts:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-03-21T04:10:20.890Z"}
{"level":"error","message":"Gemini AI analysis failed: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: fetch failed","stack":"TypeError: fetch failed\n    at node:internal/deps/undici/undici:13484:13\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at makeRequest (F:\\Github\\resume_ai\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:397:20)\n    at generateContent (F:\\Github\\resume_ai\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:867:22)","timestamp":"2025-03-21T07:13:23.899Z"}
{"level":"error","message":"Gemini AI analysis failed: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent: fetch failed","stack":"TypeError: fetch failed\n    at node:internal/deps/undici/undici:13484:13\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at makeRequest (F:\\Github\\resume_ai\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:397:20)\n    at generateContent (F:\\Github\\resume_ai\\backend\\node_modules\\@google\\generative-ai\\dist\\index.js:867:22)","timestamp":"2025-03-21T08:30:35.104Z"}
